/**
 * Seed universe_members with actual Nifty index constituents.
 *
 * Each stock is stored ONCE under its most granular universe tag.
 * Composite indices (Nifty 100 = nifty50 + niftynext50) are resolved at query time.
 *
 * Usage:  npx tsx api/prisma/seed.ts
 */

import { PrismaClient } from "../src/generated/prisma/client.js"
import { PrismaPg } from "@prisma/adapter-pg"
import "dotenv/config"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter } as any)

type Member = { universe: string; symbol: string; name: string; sector: string }

// ── Nifty 50 (50 stocks) ──────────────────────────────────────────
const NIFTY_50: Member[] = [
  { universe: "nifty50", symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Metals & Mining" },
  { universe: "nifty50", symbol: "ADANIPORTS.NS", name: "Adani Ports & SEZ", sector: "Infrastructure" },
  { universe: "nifty50", symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare" },
  { universe: "nifty50", symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Auto & Ancillaries" },
  { universe: "nifty50", symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "BEL.NS", name: "Bharat Electronics", sector: "Industrials" },
  { universe: "nifty50", symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Communication Services" },
  { universe: "nifty50", symbol: "CIPLA.NS", name: "Cipla", sector: "Healthcare" },
  { universe: "nifty50", symbol: "COALINDIA.NS", name: "Coal India", sector: "Metals & Mining" },
  { universe: "nifty50", symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories", sector: "Healthcare" },
  { universe: "nifty50", symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Auto & Ancillaries" },
  { universe: "nifty50", symbol: "ETERNAL.NS", name: "Eternal (Zomato)", sector: "Services" },
  { universe: "nifty50", symbol: "GRASIM.NS", name: "Grasim Industries", sector: "Materials" },
  { universe: "nifty50", symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "IT & Software" },
  { universe: "nifty50", symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "HINDALCO.NS", name: "Hindalco Industries", sector: "Metals & Mining" },
  { universe: "nifty50", symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "INDIGO.NS", name: "InterGlobe Aviation", sector: "Services" },
  { universe: "nifty50", symbol: "INFY.NS", name: "Infosys", sector: "IT & Software" },
  { universe: "nifty50", symbol: "ITC.NS", name: "ITC", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "JIOFIN.NS", name: "Jio Financial Services", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Metals & Mining" },
  { universe: "nifty50", symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "LT.NS", name: "Larsen & Toubro", sector: "Industrials" },
  { universe: "nifty50", symbol: "M&M.NS", name: "Mahindra & Mahindra", sector: "Auto & Ancillaries" },
  { universe: "nifty50", symbol: "MARUTI.NS", name: "Maruti Suzuki", sector: "Auto & Ancillaries" },
  { universe: "nifty50", symbol: "MAXHEALTH.NS", name: "Max Healthcare", sector: "Healthcare" },
  { universe: "nifty50", symbol: "NESTLEIND.NS", name: "Nestle India", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "NTPC.NS", name: "NTPC", sector: "Energy & Power" },
  { universe: "nifty50", symbol: "ONGC.NS", name: "Oil & Natural Gas Corp.", sector: "Energy & Power" },
  { universe: "nifty50", symbol: "POWERGRID.NS", name: "Power Grid Corp.", sector: "Energy & Power" },
  { universe: "nifty50", symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy & Power" },
  { universe: "nifty50", symbol: "SBILIFE.NS", name: "SBI Life Insurance", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "SBIN.NS", name: "State Bank of India", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "SHRIRAMFIN.NS", name: "Shriram Finance", sector: "Banking & Finance" },
  { universe: "nifty50", symbol: "SUNPHARMA.NS", name: "Sun Pharma", sector: "Healthcare" },
  { universe: "nifty50", symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Metals & Mining" },
  { universe: "nifty50", symbol: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "IT & Software" },
  { universe: "nifty50", symbol: "TECHM.NS", name: "Tech Mahindra", sector: "IT & Software" },
  { universe: "nifty50", symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "TMPV.NS", name: "TM Pvt Ltd", sector: "Auto & Ancillaries" },
  { universe: "nifty50", symbol: "TRENT.NS", name: "Trent", sector: "Consumer Goods" },
  { universe: "nifty50", symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Materials" },
  { universe: "nifty50", symbol: "WIPRO.NS", name: "Wipro", sector: "IT & Software" },
]

// ── Nifty Next 50 (50 stocks, NOT in Nifty 50) ────────────────────
const NIFTY_NEXT_50: Member[] = [
  { universe: "niftynext50", symbol: "ABB.NS", name: "ABB India", sector: "Industrials" },
  { universe: "niftynext50", symbol: "ADANIGREEN.NS", name: "Adani Green Energy", sector: "Energy & Power" },
  { universe: "niftynext50", symbol: "AMBUJACEM.NS", name: "Ambuja Cements", sector: "Materials" },
  { universe: "niftynext50", symbol: "ATGL.NS", name: "Adani Total Gas", sector: "Energy & Power" },
  { universe: "niftynext50", symbol: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Banking & Finance" },

  { universe: "niftynext50", symbol: "BOSCHLTD.NS", name: "Bosch", sector: "Auto & Ancillaries" },
  { universe: "niftynext50", symbol: "CANBK.NS", name: "Canara Bank", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "COLPAL.NS", name: "Colgate-Palmolive India", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "DLF.NS", name: "DLF", sector: "Real Estate" },
  { universe: "niftynext50", symbol: "GAIL.NS", name: "GAIL India", sector: "Energy & Power" },
  { universe: "niftynext50", symbol: "GODREJCP.NS", name: "Godrej Consumer Products", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "HAL.NS", name: "Hindustan Aeronautics", sector: "Industrials" },
  { universe: "niftynext50", symbol: "HAVELLS.NS", name: "Havells India", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life", sector: "Banking & Finance" },

  { universe: "niftynext50", symbol: "IOC.NS", name: "Indian Oil Corp.", sector: "Energy & Power" },
  { universe: "niftynext50", symbol: "IRCTC.NS", name: "IRCTC", sector: "Services" },
  { universe: "niftynext50", symbol: "IRFC.NS", name: "Indian Railway Finance", sector: "Banking & Finance" },

  { universe: "niftynext50", symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power", sector: "Metals & Mining" },
  { universe: "niftynext50", symbol: "LICI.NS", name: "Life Insurance Corp.", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "LUPIN.NS", name: "Lupin", sector: "Healthcare" },
  { universe: "niftynext50", symbol: "MARICO.NS", name: "Marico", sector: "Consumer Goods" },

  { universe: "niftynext50", symbol: "NAUKRI.NS", name: "Info Edge (Naukri)", sector: "IT & Software" },
  { universe: "niftynext50", symbol: "PFC.NS", name: "Power Finance Corp.", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Materials" },
  { universe: "niftynext50", symbol: "PNB.NS", name: "Punjab National Bank", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "RECLTD.NS", name: "REC", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "SAIL.NS", name: "Steel Authority of India", sector: "Metals & Mining" },
  { universe: "niftynext50", symbol: "SBICARD.NS", name: "SBI Cards", sector: "Banking & Finance" },
  { universe: "niftynext50", symbol: "SIEMENS.NS", name: "Siemens", sector: "Industrials" },
  { universe: "niftynext50", symbol: "SRF.NS", name: "SRF", sector: "Materials" },
  { universe: "niftynext50", symbol: "TATAPOWER.NS", name: "Tata Power", sector: "Energy & Power" },
  { universe: "niftynext50", symbol: "TORNTPHARM.NS", name: "Torrent Pharma", sector: "Healthcare" },

  { universe: "niftynext50", symbol: "UNITDSPR.NS", name: "United Spirits", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "VBL.NS", name: "Varun Beverages", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "VEDL.NS", name: "Vedanta", sector: "Metals & Mining" },
  { universe: "niftynext50", symbol: "ZOMATO.NS", name: "Zomato", sector: "Services" },
  { universe: "niftynext50", symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences", sector: "Healthcare" },
  { universe: "niftynext50", symbol: "DMART.NS", name: "Avenue Supermarts (DMart)", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "DABUR.NS", name: "Dabur India", sector: "Consumer Goods" },
  { universe: "niftynext50", symbol: "INDUSTOWER.NS", name: "Indus Towers", sector: "Communication Services" },
  { universe: "niftynext50", symbol: "MOTHERSON.NS", name: "Samvardhana Motherson", sector: "Auto & Ancillaries" },
  { universe: "niftynext50", symbol: "NHPC.NS", name: "NHPC", sector: "Energy & Power" },
  { universe: "niftynext50", symbol: "POLYCAB.NS", name: "Polycab India", sector: "Industrials" },
  { universe: "niftynext50", symbol: "TVSMOTOR.NS", name: "TVS Motor Company", sector: "Auto & Ancillaries" },
]

// ── Nifty 200 extras (stocks in Nifty 200 but NOT in Nifty 100) ──
const NIFTY_200_EXTRA: Member[] = [
  { universe: "nifty200", symbol: "ACC.NS", name: "ACC", sector: "Materials" },
  { universe: "nifty200", symbol: "ALKEM.NS", name: "Alkem Laboratories", sector: "Healthcare" },
  { universe: "nifty200", symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes", sector: "Metals & Mining" },
  { universe: "nifty200", symbol: "ASTRAL.NS", name: "Astral", sector: "Industrials" },
  { universe: "nifty200", symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma", sector: "Healthcare" },
  { universe: "nifty200", symbol: "BALKRISIND.NS", name: "Balkrishna Industries", sector: "Auto & Ancillaries" },
  { universe: "nifty200", symbol: "BANDHANBNK.NS", name: "Bandhan Bank", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "BERGEPAINT.NS", name: "Berger Paints", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "BHEL.NS", name: "Bharat Heavy Electricals", sector: "Industrials" },
  { universe: "nifty200", symbol: "BIOCON.NS", name: "Biocon", sector: "Healthcare" },
  { universe: "nifty200", symbol: "CAMS.NS", name: "Computer Age Mgmt Services", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "CGPOWER.NS", name: "CG Power & Industrial", sector: "Industrials" },
  { universe: "nifty200", symbol: "COFORGE.NS", name: "Coforge", sector: "IT & Software" },
  { universe: "nifty200", symbol: "CONCOR.NS", name: "Container Corp. of India", sector: "Infrastructure" },
  { universe: "nifty200", symbol: "CROMPTON.NS", name: "Crompton Greaves Consumer", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "CUMMINSIND.NS", name: "Cummins India", sector: "Industrials" },
  { universe: "nifty200", symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite", sector: "Materials" },
  { universe: "nifty200", symbol: "DELHIVERY.NS", name: "Delhivery", sector: "Services" },
  { universe: "nifty200", symbol: "DIXON.NS", name: "Dixon Technologies", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "ESCORTS.NS", name: "Escorts Kubota", sector: "Auto & Ancillaries" },
  { universe: "nifty200", symbol: "FEDERALBNK.NS", name: "Federal Bank", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "FORTIS.NS", name: "Fortis Healthcare", sector: "Healthcare" },
  { universe: "nifty200", symbol: "GLAND.NS", name: "Gland Pharma", sector: "Healthcare" },
  { universe: "nifty200", symbol: "GLENMARK.NS", name: "Glenmark Pharma", sector: "Healthcare" },
  { universe: "nifty200", symbol: "GMRINFRA.NS", name: "GMR Airports Infra", sector: "Infrastructure" },
  { universe: "nifty200", symbol: "HINDPETRO.NS", name: "Hindustan Petroleum", sector: "Energy & Power" },
  { universe: "nifty200", symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "IIFL.NS", name: "IIFL Finance", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "INDHOTEL.NS", name: "Indian Hotels", sector: "Services" },
  { universe: "nifty200", symbol: "IPCALAB.NS", name: "IPCA Laboratories", sector: "Healthcare" },
  { universe: "nifty200", symbol: "JSL.NS", name: "Jindal Stainless", sector: "Metals & Mining" },
  { universe: "nifty200", symbol: "JUBLFOOD.NS", name: "Jubilant FoodWorks", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "KALYANKJIL.NS", name: "Kalyan Jewellers", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "LICHSGFIN.NS", name: "LIC Housing Finance", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "LTTS.NS", name: "L&T Technology Services", sector: "IT & Software" },
  { universe: "nifty200", symbol: "LODHA.NS", name: "Macrotech Developers", sector: "Real Estate" },
  { universe: "nifty200", symbol: "MANKIND.NS", name: "Mankind Pharma", sector: "Healthcare" },
  { universe: "nifty200", symbol: "MFSL.NS", name: "Max Financial Services", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "MRF.NS", name: "MRF", sector: "Auto & Ancillaries" },
  { universe: "nifty200", symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "NMDC.NS", name: "NMDC", sector: "Metals & Mining" },
  { universe: "nifty200", symbol: "OBEROIRLTY.NS", name: "Oberoi Realty", sector: "Real Estate" },
  { universe: "nifty200", symbol: "OFSS.NS", name: "Oracle Financial Services", sector: "IT & Software" },
  { universe: "nifty200", symbol: "PAGEIND.NS", name: "Page Industries", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "PAYTM.NS", name: "One97 Communications", sector: "IT & Software" },
  { universe: "nifty200", symbol: "PERSISTENT.NS", name: "Persistent Systems", sector: "IT & Software" },
  { universe: "nifty200", symbol: "PETRONET.NS", name: "Petronet LNG", sector: "Energy & Power" },
  { universe: "nifty200", symbol: "PIIND.NS", name: "PI Industries", sector: "Materials" },
  { universe: "nifty200", symbol: "PRESTIGE.NS", name: "Prestige Estates", sector: "Real Estate" },
  { universe: "nifty200", symbol: "PVRCINEMAS.NS", name: "PVR INOX", sector: "Services" },
  { universe: "nifty200", symbol: "RAMCOCEM.NS", name: "Ramco Cements", sector: "Materials" },
  { universe: "nifty200", symbol: "SOLARINDS.NS", name: "Solar Industries", sector: "Materials" },
  { universe: "nifty200", symbol: "SONACOMS.NS", name: "Sona BLW Precision", sector: "Auto & Ancillaries" },
  { universe: "nifty200", symbol: "STARHEALTH.NS", name: "Star Health Insurance", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "SUNDARMFIN.NS", name: "Sundaram Finance", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "SUPREMEIND.NS", name: "Supreme Industries", sector: "Industrials" },
  { universe: "nifty200", symbol: "SYNGENE.NS", name: "Syngene International", sector: "Healthcare" },
  { universe: "nifty200", symbol: "TATACHEM.NS", name: "Tata Chemicals", sector: "Materials" },
  { universe: "nifty200", symbol: "TATACOMM.NS", name: "Tata Communications", sector: "Communication Services" },
  { universe: "nifty200", symbol: "TATAELXSI.NS", name: "Tata Elxsi", sector: "IT & Software" },
  { universe: "nifty200", symbol: "THERMAX.NS", name: "Thermax", sector: "Industrials" },
  { universe: "nifty200", symbol: "TIINDIA.NS", name: "Tube Investments", sector: "Industrials" },
  { universe: "nifty200", symbol: "TORNTPOWER.NS", name: "Torrent Power", sector: "Energy & Power" },
  { universe: "nifty200", symbol: "TTML.NS", name: "Tata Teleservices Maha", sector: "Communication Services" },
  { universe: "nifty200", symbol: "UPL.NS", name: "UPL", sector: "Materials" },
  { universe: "nifty200", symbol: "VOLTAS.NS", name: "Voltas", sector: "Consumer Goods" },
  { universe: "nifty200", symbol: "YESBANK.NS", name: "Yes Bank", sector: "Banking & Finance" },
  { universe: "nifty200", symbol: "ZEEL.NS", name: "Zee Entertainment", sector: "Communication Services" },
]

// ── Nifty Midcap 50 ──────────────────────────────────────────────
const NIFTY_MIDCAP_50: Member[] = [
  { universe: "niftymidcap50", symbol: "AARTIIND.NS", name: "Aarti Industries", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "AUBANK.NS", name: "AU Small Finance Bank", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "BATAINDIA.NS", name: "Bata India", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "BHARATFORG.NS", name: "Bharat Forge", sector: "Industrials" },
  { universe: "niftymidcap50", symbol: "CANFINHOME.NS", name: "Can Fin Homes", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "COROMANDEL.NS", name: "Coromandel International", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "CYIENT.NS", name: "Cyient", sector: "IT & Software" },
  { universe: "niftymidcap50", symbol: "EMAMILTD.NS", name: "Emami", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "EXIDEIND.NS", name: "Exide Industries", sector: "Auto & Ancillaries" },
  { universe: "niftymidcap50", symbol: "GMMPFAUDLR.NS", name: "GMM Pfaudler", sector: "Industrials" },
  { universe: "niftymidcap50", symbol: "GODREJPROP.NS", name: "Godrej Properties", sector: "Real Estate" },
  { universe: "niftymidcap50", symbol: "GSPL.NS", name: "Gujarat State Petronet", sector: "Energy & Power" },
  { universe: "niftymidcap50", symbol: "HONAUT.NS", name: "Honeywell Automation", sector: "Industrials" },
  { universe: "niftymidcap50", symbol: "IBREALEST.NS", name: "Indiabulls Real Estate", sector: "Real Estate" },
  { universe: "niftymidcap50", symbol: "IDBI.NS", name: "IDBI Bank", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "INDIANB.NS", name: "Indian Bank", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "INDIACEM.NS", name: "India Cements", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "JKCEMENT.NS", name: "JK Cement", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "KPITTECH.NS", name: "KPIT Technologies", sector: "IT & Software" },
  { universe: "niftymidcap50", symbol: "L&TFH.NS", name: "L&T Finance Holdings", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "LALPATHLAB.NS", name: "Dr. Lal PathLabs", sector: "Healthcare" },
  { universe: "niftymidcap50", symbol: "MANAPPURAM.NS", name: "Manappuram Finance", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "MPHASIS.NS", name: "Mphasis", sector: "IT & Software" },
  { universe: "niftymidcap50", symbol: "NAM-INDIA.NS", name: "Nippon Life India AMC", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "NATCOPHARM.NS", name: "Natco Pharma", sector: "Healthcare" },
  { universe: "niftymidcap50", symbol: "NAVINFLUOR.NS", name: "Navin Fluorine", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "PHOENIXLTD.NS", name: "Phoenix Mills", sector: "Real Estate" },
  { universe: "niftymidcap50", symbol: "RAJESHEXPO.NS", name: "Rajesh Exports", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "RBLBANK.NS", name: "RBL Bank", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "SCHAEFFLER.NS", name: "Schaeffler India", sector: "Auto & Ancillaries" },
  { universe: "niftymidcap50", symbol: "SUNTV.NS", name: "Sun TV Network", sector: "Communication Services" },
  { universe: "niftymidcap50", symbol: "SUVENPHAR.NS", name: "Suven Pharmaceuticals", sector: "Healthcare" },
  { universe: "niftymidcap50", symbol: "TATAINVEST.NS", name: "Tata Investment Corp.", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "TRIDENT.NS", name: "Trident", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "TTKPRESTIG.NS", name: "TTK Prestige", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "TV18BRDCST.NS", name: "TV18 Broadcast", sector: "Communication Services" },
  { universe: "niftymidcap50", symbol: "VINATIORGA.NS", name: "Vinati Organics", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "WHIRLPOOL.NS", name: "Whirlpool of India", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "ZENSARTECH.NS", name: "Zensar Technologies", sector: "IT & Software" },
  { universe: "niftymidcap50", symbol: "3MINDIA.NS", name: "3M India", sector: "Industrials" },
  { universe: "niftymidcap50", symbol: "ATUL.NS", name: "Atul", sector: "Materials" },
  { universe: "niftymidcap50", symbol: "CRISIL.NS", name: "CRISIL", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "CUB.NS", name: "City Union Bank", sector: "Banking & Finance" },
  { universe: "niftymidcap50", symbol: "GILLETTE.NS", name: "Gillette India", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "GLAXO.NS", name: "GlaxoSmithKline Pharma", sector: "Healthcare" },
  { universe: "niftymidcap50", symbol: "KAJARIACER.NS", name: "Kajaria Ceramics", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "PGHH.NS", name: "Procter & Gamble Hygiene", sector: "Consumer Goods" },
  { universe: "niftymidcap50", symbol: "SANOFI.NS", name: "Sanofi India", sector: "Healthcare" },
  { universe: "niftymidcap50", symbol: "SUMICHEM.NS", name: "Sumitomo Chemical India", sector: "Materials" },
]

// ── Nifty Midcap 100 extras (in Midcap 100 but NOT in Midcap 50) ─
const NIFTY_MIDCAP_100_EXTRA: Member[] = [
  { universe: "niftymidcap100", symbol: "AJANTPHARM.NS", name: "Ajanta Pharma", sector: "Healthcare" },
  { universe: "niftymidcap100", symbol: "APLLTD.NS", name: "Alembic Pharma", sector: "Healthcare" },
  { universe: "niftymidcap100", symbol: "BASF.NS", name: "BASF India", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "BAYERCROP.NS", name: "Bayer CropScience", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "BDL.NS", name: "Bharat Dynamics", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "BLUEDART.NS", name: "Blue Dart Express", sector: "Services" },
  { universe: "niftymidcap100", symbol: "CASTROLIND.NS", name: "Castrol India", sector: "Energy & Power" },
  { universe: "niftymidcap100", symbol: "CENTURYTEX.NS", name: "Century Textiles", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "CHAMBLFERT.NS", name: "Chambal Fertilisers", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "CLEAN.NS", name: "Clean Science & Tech", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "COCHINSHIP.NS", name: "Cochin Shipyard", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "DEVYANI.NS", name: "Devyani International", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "ELGIEQUIP.NS", name: "Elgi Equipments", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "ENDURANCE.NS", name: "Endurance Technologies", sector: "Auto & Ancillaries" },
  { universe: "niftymidcap100", symbol: "FACT.NS", name: "Fertilisers & Chemicals", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "FINEORG.NS", name: "Fine Organic Industries", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "GRINDWELL.NS", name: "Grindwell Norton", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "GSFC.NS", name: "Gujarat State Fertilizers", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "HATSUN.NS", name: "Hatsun Agro Product", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "ICICIGI.NS", name: "ICICI Lombard General", sector: "Banking & Finance" },
  { universe: "niftymidcap100", symbol: "JBCHEPHARM.NS", name: "JB Chemicals & Pharma", sector: "Healthcare" },
  { universe: "niftymidcap100", symbol: "JSWENERGY.NS", name: "JSW Energy", sector: "Energy & Power" },
  { universe: "niftymidcap100", symbol: "JUSTDIAL.NS", name: "Just Dial", sector: "IT & Software" },
  { universe: "niftymidcap100", symbol: "KANSAINER.NS", name: "Kansai Nerolac Paints", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "KEI.NS", name: "KEI Industries", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "METROPOLIS.NS", name: "Metropolis Healthcare", sector: "Healthcare" },
  { universe: "niftymidcap100", symbol: "MSUMI.NS", name: "Motherson Sumi Wiring", sector: "Auto & Ancillaries" },
  { universe: "niftymidcap100", symbol: "NIACL.NS", name: "New India Assurance", sector: "Banking & Finance" },
  { universe: "niftymidcap100", symbol: "NLCINDIA.NS", name: "NLC India", sector: "Energy & Power" },
  { universe: "niftymidcap100", symbol: "POLYMED.NS", name: "Poly Medicure", sector: "Healthcare" },
  { universe: "niftymidcap100", symbol: "RADICO.NS", name: "Radico Khaitan", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "ROUTE.NS", name: "Route Mobile", sector: "IT & Software" },
  { universe: "niftymidcap100", symbol: "SAPPHIRE.NS", name: "Sapphire Foods India", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "SHREECEM.NS", name: "Shree Cement", sector: "Materials" },
  { universe: "niftymidcap100", symbol: "SJVN.NS", name: "SJVN", sector: "Energy & Power" },
  { universe: "niftymidcap100", symbol: "SKFINDIA.NS", name: "SKF India", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "SUNDRMFAST.NS", name: "Sundram Fasteners", sector: "Auto & Ancillaries" },
  { universe: "niftymidcap100", symbol: "TATAMETALI.NS", name: "Tata Metaliks", sector: "Metals & Mining" },
  { universe: "niftymidcap100", symbol: "TIMKEN.NS", name: "Timken India", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "UJJIVANSFB.NS", name: "Ujjivan Small Finance", sector: "Banking & Finance" },
  { universe: "niftymidcap100", symbol: "VAIBHAVGBL.NS", name: "Vaibhav Global", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "VGUARD.NS", name: "V-Guard Industries", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "VIPIND.NS", name: "VIP Industries", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "VSTIND.NS", name: "VST Industries", sector: "Consumer Goods" },
  { universe: "niftymidcap100", symbol: "WELCORP.NS", name: "Welspun Corp", sector: "Metals & Mining" },
  { universe: "niftymidcap100", symbol: "ZFCVINDIA.NS", name: "ZF Commercial Vehicles", sector: "Auto & Ancillaries" },
  { universe: "niftymidcap100", symbol: "HAPPSTMNDS.NS", name: "Happiest Minds Tech", sector: "IT & Software" },
  { universe: "niftymidcap100", symbol: "MAZDOCK.NS", name: "Mazagon Dock Shipbuilders", sector: "Industrials" },
  { universe: "niftymidcap100", symbol: "RVNL.NS", name: "Rail Vikas Nigam", sector: "Infrastructure" },
  { universe: "niftymidcap100", symbol: "IREDA.NS", name: "Indian Renewable Energy", sector: "Banking & Finance" },
]

// ── Nifty Smallcap 50 ────────────────────────────────────────────
const NIFTY_SMALLCAP_50: Member[] = [
  { universe: "niftysmallcap50", symbol: "ALOKINDS.NS", name: "Alok Industries", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "BSOFT.NS", name: "Birlasoft", sector: "IT & Software" },
  { universe: "niftysmallcap50", symbol: "CAMPUS.NS", name: "Campus Activewear", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "CDSL.NS", name: "CDSL", sector: "Banking & Finance" },
  { universe: "niftysmallcap50", symbol: "DATAPATTNS.NS", name: "Data Patterns", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "ERIS.NS", name: "Eris Lifesciences", sector: "Healthcare" },
  { universe: "niftysmallcap50", symbol: "FINCABLES.NS", name: "Finolex Cables", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "FINPIPE.NS", name: "Finolex Industries", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "GHCL.NS", name: "GHCL", sector: "Materials" },
  { universe: "niftysmallcap50", symbol: "GPPL.NS", name: "Gujarat Pipavav Port", sector: "Infrastructure" },
  { universe: "niftysmallcap50", symbol: "GRSE.NS", name: "Garden Reach Shipbuilders", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "HGS.NS", name: "Hinduja Global Solutions", sector: "IT & Software" },
  { universe: "niftysmallcap50", symbol: "HFCL.NS", name: "HFCL", sector: "Communication Services" },
  { universe: "niftysmallcap50", symbol: "IIFLWAM.NS", name: "IIFL Wealth Management", sector: "Banking & Finance" },
  { universe: "niftysmallcap50", symbol: "INOXWIND.NS", name: "Inox Wind", sector: "Energy & Power" },
  { universe: "niftysmallcap50", symbol: "JKLAKSHMI.NS", name: "JK Lakshmi Cement", sector: "Materials" },
  { universe: "niftysmallcap50", symbol: "JMFINANCIL.NS", name: "JM Financial", sector: "Banking & Finance" },
  { universe: "niftysmallcap50", symbol: "JYOTHYLAB.NS", name: "Jyothy Labs", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "KEC.NS", name: "KEC International", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "LEMONTREE.NS", name: "Lemon Tree Hotels", sector: "Services" },
  { universe: "niftysmallcap50", symbol: "LTFOODS.NS", name: "LT Foods", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "MASFIN.NS", name: "MAS Financial Services", sector: "Banking & Finance" },
  { universe: "niftysmallcap50", symbol: "MEDANTA.NS", name: "Medanta (Global Health)", sector: "Healthcare" },
  { universe: "niftysmallcap50", symbol: "MMTC.NS", name: "MMTC", sector: "Metals & Mining" },
  { universe: "niftysmallcap50", symbol: "NBCC.NS", name: "NBCC (India)", sector: "Infrastructure" },
  { universe: "niftysmallcap50", symbol: "NESCO.NS", name: "Nesco", sector: "Real Estate" },
  { universe: "niftysmallcap50", symbol: "OLECTRA.NS", name: "Olectra Greentech", sector: "Auto & Ancillaries" },
  { universe: "niftysmallcap50", symbol: "ORIENTELEC.NS", name: "Orient Electric", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "PRINCEPIPE.NS", name: "Prince Pipes", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "PVRINOX.NS", name: "PVR INOX", sector: "Services" },
  { universe: "niftysmallcap50", symbol: "RATNAMANI.NS", name: "Ratnamani Metals", sector: "Metals & Mining" },
  { universe: "niftysmallcap50", symbol: "RELIGARE.NS", name: "Religare Enterprises", sector: "Banking & Finance" },
  { universe: "niftysmallcap50", symbol: "RITES.NS", name: "RITES", sector: "Infrastructure" },
  { universe: "niftysmallcap50", symbol: "SAFARI.NS", name: "Safari Industries", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "SWANENERGY.NS", name: "Swan Energy", sector: "Energy & Power" },
  { universe: "niftysmallcap50", symbol: "TANLA.NS", name: "Tanla Platforms", sector: "IT & Software" },
  { universe: "niftysmallcap50", symbol: "TEAMLEASE.NS", name: "TeamLease Services", sector: "Services" },
  { universe: "niftysmallcap50", symbol: "TITAGARH.NS", name: "Titagarh Rail Systems", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "TRITURBINE.NS", name: "Triveni Turbine", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "WABAG.NS", name: "VA Tech Wabag", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "WELSPUNLIV.NS", name: "Welspun Living", sector: "Consumer Goods" },
  { universe: "niftysmallcap50", symbol: "ZENTEC.NS", name: "Zen Technologies", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "AFFLE.NS", name: "Affle India", sector: "IT & Software" },
  { universe: "niftysmallcap50", symbol: "APTUS.NS", name: "Aptus Value Housing", sector: "Banking & Finance" },
  { universe: "niftysmallcap50", symbol: "CESC.NS", name: "CESC", sector: "Energy & Power" },
  { universe: "niftysmallcap50", symbol: "CHEMPLASTS.NS", name: "Chemplast Sanmar", sector: "Materials" },
  { universe: "niftysmallcap50", symbol: "CRAFTSMAN.NS", name: "Craftsman Automation", sector: "Industrials" },
  { universe: "niftysmallcap50", symbol: "EASEMYTRIP.NS", name: "Easy Trip Planners", sector: "Services" },
  { universe: "niftysmallcap50", symbol: "ELECTCAST.NS", name: "Electrosteel Castings", sector: "Metals & Mining" },
  { universe: "niftysmallcap50", symbol: "HUDCO.NS", name: "HUDCO", sector: "Banking & Finance" },
]

// ── Nifty Smallcap 100 extras (in Smallcap 100 but NOT in Smallcap 50) ─
const NIFTY_SMALLCAP_100_EXTRA: Member[] = [
  { universe: "niftysmallcap100", symbol: "AMBER.NS", name: "Amber Enterprises", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "ANURAS.NS", name: "Anupam Rasayan", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "BALAMINES.NS", name: "Balaji Amines", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "BLUESTARCO.NS", name: "Blue Star", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "CARERATING.NS", name: "CARE Ratings", sector: "Banking & Finance" },
  { universe: "niftysmallcap100", symbol: "CENTURYPLY.NS", name: "Century Plyboards", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "CMSINFO.NS", name: "CMS Info Systems", sector: "IT & Software" },
  { universe: "niftysmallcap100", symbol: "DOMS.NS", name: "DOMS Industries", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "ECLERX.NS", name: "eClerx Services", sector: "IT & Software" },
  { universe: "niftysmallcap100", symbol: "EPL.NS", name: "EPL", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "EIDPARRY.NS", name: "EID Parry", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "GESHIP.NS", name: "Great Eastern Shipping", sector: "Services" },
  { universe: "niftysmallcap100", symbol: "GOCOLORS.NS", name: "Go Fashion (India)", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "GODFRYPHLP.NS", name: "Godfrey Phillips", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "GREENPLY.NS", name: "Greenply Industries", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "HEMIPROP.NS", name: "Hemisphere Properties", sector: "Real Estate" },
  { universe: "niftysmallcap100", symbol: "HLEGLAS.NS", name: "HLE Glascoat", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "IDFC.NS", name: "IDFC", sector: "Banking & Finance" },
  { universe: "niftysmallcap100", symbol: "JINDALSAW.NS", name: "Jindal Saw", sector: "Metals & Mining" },
  { universe: "niftysmallcap100", symbol: "JKPAPER.NS", name: "JK Paper", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "KAYNES.NS", name: "Kaynes Technology", sector: "IT & Software" },
  { universe: "niftysmallcap100", symbol: "KIRLOSENG.NS", name: "Kirloskar Oil Engines", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "KRBL.NS", name: "KRBL", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "LATENTVIEW.NS", name: "Latent View Analytics", sector: "IT & Software" },
  { universe: "niftysmallcap100", symbol: "MAHSEAMLES.NS", name: "Maharashtra Seamless", sector: "Metals & Mining" },
  { universe: "niftysmallcap100", symbol: "MASTEK.NS", name: "Mastek", sector: "IT & Software" },
  { universe: "niftysmallcap100", symbol: "METROPOLIS.NS", name: "Metropolis Healthcare", sector: "Healthcare" },
  { universe: "niftysmallcap100", symbol: "MONTECARLO.NS", name: "Monte Carlo Fashions", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "NETWORK18.NS", name: "Network18 Media", sector: "Communication Services" },
  { universe: "niftysmallcap100", symbol: "PNBHOUSING.NS", name: "PNB Housing Finance", sector: "Banking & Finance" },
  { universe: "niftysmallcap100", symbol: "POWERINDIA.NS", name: "Hitachi Energy India", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "PRICOLLTD.NS", name: "Pricol", sector: "Auto & Ancillaries" },
  { universe: "niftysmallcap100", symbol: "RAYMOND.NS", name: "Raymond", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "RENUKA.NS", name: "Shree Renuka Sugars", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "ROSSARI.NS", name: "Rossari Biotech", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "RPOWER.NS", name: "Reliance Power", sector: "Energy & Power" },
  { universe: "niftysmallcap100", symbol: "SOBHA.NS", name: "Sobha", sector: "Real Estate" },
  { universe: "niftysmallcap100", symbol: "STARCEMENT.NS", name: "Star Cement", sector: "Materials" },
  { universe: "niftysmallcap100", symbol: "TDPOWERSYS.NS", name: "TD Power Systems", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "TECHNOE.NS", name: "Techno Electric & Eng.", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "TRIVENI.NS", name: "Triveni Engineering", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "TVSSRICHAK.NS", name: "TVS Srichakra", sector: "Auto & Ancillaries" },
  { universe: "niftysmallcap100", symbol: "VARROC.NS", name: "Varroc Engineering", sector: "Auto & Ancillaries" },
  { universe: "niftysmallcap100", symbol: "WESTLIFE.NS", name: "Westlife Foodworld", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "ZENSARTECH.NS", name: "Zensar Technologies", sector: "IT & Software" },
  { universe: "niftysmallcap100", symbol: "BORORENEW.NS", name: "Borosil Renewables", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "CERA.NS", name: "Cera Sanitaryware", sector: "Consumer Goods" },
  { universe: "niftysmallcap100", symbol: "ENGINERSIN.NS", name: "Engineers India", sector: "Industrials" },
  { universe: "niftysmallcap100", symbol: "FIVESTAR.NS", name: "Five-Star Business Finance", sector: "Banking & Finance" },
  { universe: "niftysmallcap100", symbol: "GALAXYSURF.NS", name: "Galaxy Surfactants", sector: "Materials" },
]

// ── Combine all ──────────────────────────────────────────────────
// US indices (sp100, nasdaq100) will be added later via CSV sync.

const ALL_MEMBERS: Member[] = [
  ...NIFTY_50,
  ...NIFTY_NEXT_50,
  ...NIFTY_200_EXTRA,
  ...NIFTY_MIDCAP_50,
  ...NIFTY_MIDCAP_100_EXTRA,
  ...NIFTY_SMALLCAP_50,
  ...NIFTY_SMALLCAP_100_EXTRA,
]

async function main() {
  console.log("[Seed] Seeding universe_members...")
  console.log(`  Nifty 50:           ${NIFTY_50.length}`)
  console.log(`  Nifty Next 50:      ${NIFTY_NEXT_50.length}`)
  console.log(`  Nifty 200 extra:    ${NIFTY_200_EXTRA.length}`)
  console.log(`  Midcap 50:          ${NIFTY_MIDCAP_50.length}`)
  console.log(`  Midcap 100 extra:   ${NIFTY_MIDCAP_100_EXTRA.length}`)
  console.log(`  Smallcap 50:        ${NIFTY_SMALLCAP_50.length}`)
  console.log(`  Smallcap 100 extra: ${NIFTY_SMALLCAP_100_EXTRA.length}`)
  console.log(`  Total:              ${ALL_MEMBERS.length}`)

  const result = await prisma.universeMember.createMany({
    data: ALL_MEMBERS,
    skipDuplicates: true,
  })

  console.log(`\n[Seed] Inserted ${result.count} universe members (skipped duplicates).`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
